# Generated by Django 4.0 on 2021-12-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
